version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - nilerr
    - misspell
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kurt4ins/vk-segmentation

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
