// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kurt4ins/vk-segmentation/internal/service (interfaces: SegmentRepository,UserRepository,MembershipRepository,HistoryRepository,HistoryReader,RolloutEnqueuer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/kurt4ins/vk-segmentation/internal/service SegmentRepository,UserRepository,MembershipRepository,HistoryRepository,HistoryReader,RolloutEnqueuer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/kurt4ins/vk-segmentation/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSegmentRepository is a mock of SegmentRepository interface.
type MockSegmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentRepositoryMockRecorder
	isgomock struct{}
}

// MockSegmentRepositoryMockRecorder is the mock recorder for MockSegmentRepository.
type MockSegmentRepositoryMockRecorder struct {
	mock *MockSegmentRepository
}

// NewMockSegmentRepository creates a new mock instance.
func NewMockSegmentRepository(ctrl *gomock.Controller) *MockSegmentRepository {
	mock := &MockSegmentRepository{ctrl: ctrl}
	mock.recorder = &MockSegmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentRepository) EXPECT() *MockSegmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSegmentRepository) Create(ctx context.Context, slug string, autoPercent *int) (domain.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, slug, autoPercent)
	ret0, _ := ret[0].(domain.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSegmentRepositoryMockRecorder) Create(ctx, slug, autoPercent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSegmentRepository)(nil).Create), ctx, slug, autoPercent)
}

// DeleteMembershipsBySegment mocks base method.
func (m *MockSegmentRepository) DeleteMembershipsBySegment(ctx context.Context, segmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMembershipsBySegment", ctx, segmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMembershipsBySegment indicates an expected call of DeleteMembershipsBySegment.
func (mr *MockSegmentRepositoryMockRecorder) DeleteMembershipsBySegment(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMembershipsBySegment", reflect.TypeOf((*MockSegmentRepository)(nil).DeleteMembershipsBySegment), ctx, segmentID)
}

// GetBySlug mocks base method.
func (m *MockSegmentRepository) GetBySlug(ctx context.Context, slug string) (domain.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(domain.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockSegmentRepositoryMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockSegmentRepository)(nil).GetBySlug), ctx, slug)
}

// List mocks base method.
func (m *MockSegmentRepository) List(ctx context.Context) ([]domain.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSegmentRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSegmentRepository)(nil).List), ctx)
}

// ListBySlugs mocks base method.
func (m *MockSegmentRepository) ListBySlugs(ctx context.Context, slugs []string) ([]domain.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySlugs", ctx, slugs)
	ret0, _ := ret[0].([]domain.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySlugs indicates an expected call of ListBySlugs.
func (mr *MockSegmentRepositoryMockRecorder) ListBySlugs(ctx, slugs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySlugs", reflect.TypeOf((*MockSegmentRepository)(nil).ListBySlugs), ctx, slugs)
}

// ListMemberUserIDs mocks base method.
func (m *MockSegmentRepository) ListMemberUserIDs(ctx context.Context, segmentID int64) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMemberUserIDs", ctx, segmentID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMemberUserIDs indicates an expected call of ListMemberUserIDs.
func (mr *MockSegmentRepositoryMockRecorder) ListMemberUserIDs(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMemberUserIDs", reflect.TypeOf((*MockSegmentRepository)(nil).ListMemberUserIDs), ctx, segmentID)
}

// ListPercentSegments mocks base method.
func (m *MockSegmentRepository) ListPercentSegments(ctx context.Context) ([]domain.Segment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPercentSegments", ctx)
	ret0, _ := ret[0].([]domain.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPercentSegments indicates an expected call of ListPercentSegments.
func (mr *MockSegmentRepositoryMockRecorder) ListPercentSegments(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPercentSegments", reflect.TypeOf((*MockSegmentRepository)(nil).ListPercentSegments), ctx)
}

// MarkApplied mocks base method.
func (m *MockSegmentRepository) MarkApplied(ctx context.Context, segmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkApplied", ctx, segmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkApplied indicates an expected call of MarkApplied.
func (mr *MockSegmentRepositoryMockRecorder) MarkApplied(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkApplied", reflect.TypeOf((*MockSegmentRepository)(nil).MarkApplied), ctx, segmentID)
}

// SoftDelete mocks base method.
func (m *MockSegmentRepository) SoftDelete(ctx context.Context, segmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, segmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockSegmentRepositoryMockRecorder) SoftDelete(ctx, segmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockSegmentRepository)(nil).SoftDelete), ctx, segmentID)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockUserRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, id uuid.UUID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, id)
}

// Exists mocks base method.
func (m *MockUserRepository) Exists(ctx context.Context, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserRepositoryMockRecorder) Exists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUserRepository)(nil).Exists), ctx, userID)
}

// ListNonMembers mocks base method.
func (m *MockUserRepository) ListNonMembers(ctx context.Context, segmentID int64, limit int) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNonMembers", ctx, segmentID, limit)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNonMembers indicates an expected call of ListNonMembers.
func (mr *MockUserRepositoryMockRecorder) ListNonMembers(ctx, segmentID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNonMembers", reflect.TypeOf((*MockUserRepository)(nil).ListNonMembers), ctx, segmentID, limit)
}

// MockMembershipRepository is a mock of MembershipRepository interface.
type MockMembershipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepositoryMockRecorder
	isgomock struct{}
}

// MockMembershipRepositoryMockRecorder is the mock recorder for MockMembershipRepository.
type MockMembershipRepositoryMockRecorder struct {
	mock *MockMembershipRepository
}

// NewMockMembershipRepository creates a new mock instance.
func NewMockMembershipRepository(ctrl *gomock.Controller) *MockMembershipRepository {
	mock := &MockMembershipRepository{ctrl: ctrl}
	mock.recorder = &MockMembershipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepository) EXPECT() *MockMembershipRepositoryMockRecorder {
	return m.recorder
}

// BatchAddUsers mocks base method.
func (m *MockMembershipRepository) BatchAddUsers(ctx context.Context, segmentID int64, userIDs []uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchAddUsers", ctx, segmentID, userIDs)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchAddUsers indicates an expected call of BatchAddUsers.
func (mr *MockMembershipRepositoryMockRecorder) BatchAddUsers(ctx, segmentID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchAddUsers", reflect.TypeOf((*MockMembershipRepository)(nil).BatchAddUsers), ctx, segmentID, userIDs)
}

// BatchDelete mocks base method.
func (m *MockMembershipRepository) BatchDelete(ctx context.Context, userID uuid.UUID, segmentIDs []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", ctx, userID, segmentIDs)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockMembershipRepositoryMockRecorder) BatchDelete(ctx, userID, segmentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockMembershipRepository)(nil).BatchDelete), ctx, userID, segmentIDs)
}

// BatchInsert mocks base method.
func (m *MockMembershipRepository) BatchInsert(ctx context.Context, userID uuid.UUID, segmentIDs []int64, expiresAt *time.Time) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", ctx, userID, segmentIDs, expiresAt)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockMembershipRepositoryMockRecorder) BatchInsert(ctx, userID, segmentIDs, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockMembershipRepository)(nil).BatchInsert), ctx, userID, segmentIDs, expiresAt)
}

// DeleteExpired mocks base method.
func (m *MockMembershipRepository) DeleteExpired(ctx context.Context) ([]domain.ExpiredMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].([]domain.ExpiredMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockMembershipRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockMembershipRepository)(nil).DeleteExpired), ctx)
}

// ListActive mocks base method.
func (m *MockMembershipRepository) ListActive(ctx context.Context, userID uuid.UUID) ([]domain.ActiveSegment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx, userID)
	ret0, _ := ret[0].([]domain.ActiveSegment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockMembershipRepositoryMockRecorder) ListActive(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockMembershipRepository)(nil).ListActive), ctx, userID)
}

// MockHistoryRepository is a mock of HistoryRepository interface.
type MockHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockHistoryRepositoryMockRecorder is the mock recorder for MockHistoryRepository.
type MockHistoryRepositoryMockRecorder struct {
	mock *MockHistoryRepository
}

// NewMockHistoryRepository creates a new mock instance.
func NewMockHistoryRepository(ctrl *gomock.Controller) *MockHistoryRepository {
	mock := &MockHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryRepository) EXPECT() *MockHistoryRepositoryMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockHistoryRepository) BatchInsert(ctx context.Context, records []domain.HistoryRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", ctx, records)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockHistoryRepositoryMockRecorder) BatchInsert(ctx, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockHistoryRepository)(nil).BatchInsert), ctx, records)
}

// MockHistoryReader is a mock of HistoryReader interface.
type MockHistoryReader struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryReaderMockRecorder
	isgomock struct{}
}

// MockHistoryReaderMockRecorder is the mock recorder for MockHistoryReader.
type MockHistoryReaderMockRecorder struct {
	mock *MockHistoryReader
}

// NewMockHistoryReader creates a new mock instance.
func NewMockHistoryReader(ctrl *gomock.Controller) *MockHistoryReader {
	mock := &MockHistoryReader{ctrl: ctrl}
	mock.recorder = &MockHistoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryReader) EXPECT() *MockHistoryReaderMockRecorder {
	return m.recorder
}

// ListByUserAndRange mocks base method.
func (m *MockHistoryReader) ListByUserAndRange(ctx context.Context, userID uuid.UUID, from, to time.Time) ([]domain.HistoryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserAndRange", ctx, userID, from, to)
	ret0, _ := ret[0].([]domain.HistoryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserAndRange indicates an expected call of ListByUserAndRange.
func (mr *MockHistoryReaderMockRecorder) ListByUserAndRange(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserAndRange", reflect.TypeOf((*MockHistoryReader)(nil).ListByUserAndRange), ctx, userID, from, to)
}

// MockRolloutEnqueuer is a mock of RolloutEnqueuer interface.
type MockRolloutEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockRolloutEnqueuerMockRecorder
	isgomock struct{}
}

// MockRolloutEnqueuerMockRecorder is the mock recorder for MockRolloutEnqueuer.
type MockRolloutEnqueuerMockRecorder struct {
	mock *MockRolloutEnqueuer
}

// NewMockRolloutEnqueuer creates a new mock instance.
func NewMockRolloutEnqueuer(ctrl *gomock.Controller) *MockRolloutEnqueuer {
	mock := &MockRolloutEnqueuer{ctrl: ctrl}
	mock.recorder = &MockRolloutEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolloutEnqueuer) EXPECT() *MockRolloutEnqueuerMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockRolloutEnqueuer) Enqueue(segment domain.Segment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enqueue", segment)
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockRolloutEnqueuerMockRecorder) Enqueue(segment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockRolloutEnqueuer)(nil).Enqueue), segment)
}
